"use client";
import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, LockKeyhole, ShieldCheck } from "lucide-react";

type Mode="sign-in"|"sign-up";
export function AuthPortal({mode}:{mode:Mode}){
 const [configured,setConfigured]=useState<boolean|null>(null);const [status,setStatus]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{fetch("/api/backend-status",{cache:"no-store"}).then(r=>r.json()).then(d=>setConfigured(d.persistence==="mongodb-configured")).catch(()=>setConfigured(false))},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setStatus("");const form=new FormData(event.currentTarget);const body=Object.fromEntries(form.entries());try{const response=await fetch(`/api/auth/${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to continue");window.location.href="/console"}catch(error){setStatus(error instanceof Error?error.message:"Unable to continue")}finally{setLoading(false)}}
 return <main className="auth-shell"><section className="auth-art"><a className="auth-brand" href="/">MUNAFFA</a><div><span>PRODUCTION ACCOUNT</span><h1>{mode==="sign-up"?"Build the operating layer around your location.":"Return to your Munaffa workspace."}</h1><p>Production accounts use server-side MongoDB persistence and HTTP-only sessions when the environment is configured. The public meeting demo remains browser-local and separate.</p></div><footer><ShieldCheck size={15}/> Passwords use scrypt hashing; raw passwords are never stored.</footer></section><section className="auth-panel"><form onSubmit={submit}><div className="auth-heading"><LockKeyhole size={22}/><span>{mode==="sign-up"?"CREATE OWNER ACCOUNT":"OWNER SIGN IN"}</span><h2>{mode==="sign-up"?"Start a production workspace":"Welcome back"}</h2></div>{configured===false&&<div className="auth-config-warning"><b>Production database not configured</b><span>You can review this flow, but account creation/sign-in will stay disabled at the API boundary until MONGODB_URI is configured.</span></div>}{mode==="sign-up"&&<><label>Name<input name="name" required minLength={2} maxLength={100} autoComplete="name"/></label><label>Business name<input name="business" required minLength={2} maxLength={140}/></label><div className="auth-grid"><label>Business type<select name="businessType" defaultValue="restaurant"><option value="restaurant">Restaurant</option><option value="cafe">Café</option><option value="hotel">Hotel</option><option value="resort">Resort</option><option value="qsr">QSR</option><option value="cloud-kitchen">Cloud kitchen</option></select></label><label>City<input name="city" required minLength={2} maxLength={100}/></label></div></>}<label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Password<input name="password" type="password" required minLength={mode==="sign-up"?10:1} maxLength={128} autoComplete={mode==="sign-up"?"new-password":"current-password"}/></label><button disabled={loading||configured===false}>{loading?"Working…":mode==="sign-up"?"Create workspace":"Sign in"}<ArrowRight size={15}/></button>{status&&<p className="auth-error">{status}</p>}<p className="auth-switch">{mode==="sign-up"?<>Already have an account? <a href="/auth/sign-in">Sign in</a></>:<>Need an owner account? <a href="/auth/sign-up">Create one</a></>}</p><small>By continuing you agree to the <a href="/terms">Terms</a> and acknowledge the <a href="/privacy">Privacy notice</a>.</small></form></section></main>
}
