import { ArrowRight, Building2, ChefHat, CircleDollarSign, QrCode, ShieldCheck, Sparkles, Warehouse } from "lucide-react";

const modules=[
 {icon:QrCode,title:"Guest commerce",body:"App-free QR ordering, menu context and direct guest touchpoints."},
 {icon:ChefHat,title:"Operations",body:"Orders, kitchen/service states and staff attention queues."},
 {icon:Warehouse,title:"Cost & inventory",body:"Recipe-derived theoretical usage, purchases, physical counts and variance."},
 {icon:CircleDollarSign,title:"Profit visibility",body:"Recorded revenue/expense events and operational exposure signals."},
 {icon:Building2,title:"Multi-location",body:"One operating layer across restaurants, cafés, hotels, resorts and QSRs."},
 {icon:ShieldCheck,title:"Production boundary",body:"Role-aware architecture, audit events and explicit privacy/security requirements."}
];

export function MeetingBrief(){return <main className="meeting-shell">
 <header className="meeting-nav"><a href="/" className="meeting-brand">MUNAFFA</a><nav><a href="#product">Product</a><a href="#business">Business</a><a href="#roadmap">Roadmap</a></nav><a className="meeting-demo-link" href="/app">Open live demo <ArrowRight size={14}/></a></header>
 <section className="meeting-hero"><span>FOUNDER MEETING MODE · VALIDATION-STAGE STARTUP</span><h1>The profit operating system for modern hospitality.</h1><p>Munaffa connects the guest journey to the operating back-end: order, service, recipe cost, stock, purchasing, guest recovery and recorded money movement—so an owner can see where margin is being created or leaking.</p><div><a href="/">Cinematic experience</a><a href="/order/demo">Guest ordering</a><a href="/app">Operator workspace</a></div></section>
 <section className="meeting-band"><article><b>Problem</b><p>Hospitality data is fragmented across POS, spreadsheets, kitchen workflows, stock counts, suppliers and guest channels. Owners often see revenue faster than they see operational leakage.</p></article><article><b>Wedge</b><p>Start with small restaurants and cafés in India: shorter sales cycle, clear daily pain, easier on-site onboarding and a product that can prove value before expanding into hotels/resorts.</p></article><article><b>Positioning</b><p>Not another generic POS. Munaffa is designed around <em>profit visibility</em>: connect operational events to cost, stock and contribution while keeping counts and assumptions auditable.</p></article></section>
 <section id="product" className="meeting-section"><div className="meeting-heading"><span>01 / PRODUCT SYSTEM</span><h2>Guest experience on the surface. Operational truth underneath.</h2></div><div className="meeting-module-grid">{modules.map(({icon:Icon,title,body})=><article key={title}><Icon size={22}/><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section className="meeting-section meeting-proof"><div className="meeting-heading"><span>02 / WHY NOW</span><h2>Hospitality software is becoming an operating layer, not a single-purpose tool.</h2></div><div className="proof-grid"><article><strong>180k</strong><p>Approx. Toast locations as of June 30, 2026. It shows the scale of demand for integrated restaurant operating platforms—not Munaffa traction.</p><small>Source: Toast Q2 2026 filing</small></article><article><strong>₹5,522</strong><p>India hotel RevPAR reported for 2025, with 64% occupancy and ₹8,624 ADR. A growing hospitality market creates room for better operating technology.</p><small>Source: Horwath HTL India Hotel Market Review 2025</small></article><article><strong>Order · Pay · Engage</strong><p>Olo's modular restaurant architecture demonstrates how ordering, payments and guest engagement become a connected platform. Munaffa adds cost/inventory/profit visibility as its core wedge.</p><small>Source: Olo public filings</small></article></div></section>
 <section id="business" className="meeting-section"><div className="meeting-heading"><span>03 / BUSINESS MODEL</span><h2>Land with an owner problem. Expand with modules.</h2></div><div className="business-grid"><article><span>VALIDATION HYPOTHESIS</span><h3>Launch</h3><b>₹999 <small>/ location / month</small></b><p>Ordering + basic operations + owner overview.</p></article><article><span>VALIDATION HYPOTHESIS</span><h3>Growth</h3><b>₹2,499 <small>/ location / month</small></b><p>Inventory, recipes, purchasing, guest recovery and multi-role workflows.</p></article><article><span>VALIDATION HYPOTHESIS</span><h3>Profit</h3><b>₹4,999 <small>/ location / month</small></b><p>Profit intelligence, deeper analytics, multi-location controls and premium automation.</p></article><article><span>ENTERPRISE</span><h3>Hotels / groups</h3><b>Custom</b><p>Property workflows, integrations, service modules, onboarding and SLA requirements.</p></article></div><p className="validation-note">Pricing is a customer-discovery hypothesis, not proven willingness-to-pay. The immediate goal is 5–10 design partners and measurable operational value.</p></section>
 <section id="roadmap" className="meeting-section"><div className="meeting-heading"><span>04 / EXECUTION</span><h2>What happens after the meeting.</h2></div><ol className="roadmap-list"><li><b>Design partner discovery</b><span>Interview owners/managers; map current POS, stock, purchasing and daily closing workflow.</span></li><li><b>Pilot one location</b><span>Import menu/recipes, create QR ordering point, establish opening stock and supplier flow.</span></li><li><b>Prove one KPI</b><span>Choose a measurable target: order time, count variance, waste logging, purchasing accuracy or direct-order share.</span></li><li><b>Productise the workflow</b><span>Only automate what repeatedly creates value; integrate POS/payments after the operational wedge is validated.</span></li><li><b>Expand by location/module</b><span>Multi-location controls, CRM, hotel service workflows, intelligence and integration marketplace.</span></li></ol></section>
 <section className="meeting-section meeting-ask"><Sparkles size={28}/><span>THE ASK FOR A BUSINESS MEETING</span><h2>Give us one location, one operating pain, and enough access to measure the before/after.</h2><p>The next milestone is not a vanity user count. It is a design partner who lets Munaffa prove that connected operational data can produce a better decision or a measurable workflow improvement.</p><div><a href="/app">Run operator demo <ArrowRight size={14}/></a><a href="/order/demo">Run guest demo <ArrowRight size={14}/></a></div></section>
 <footer className="meeting-footer"><a href="/">Munaffa</a><span>Research-first meeting prototype · no fake customers, savings or integrations.</span><a href="/privacy">Privacy</a></footer>
 </main>}
