"use client";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, CircleDollarSign, ClipboardList, PackageSearch, RefreshCcw } from "lucide-react";

type Location={id:string;name:string;type:string;city:string};
type MenuItem={id:string;name:string;category:string;price:number};
type InventoryItem={id:string;name:string;unit:string;theoreticalQty:number;physicalQty:number;reorderPoint:number;unitCost:number};
type Order={id:string;status:string;channel:string;tableLabel?:string|null;guestName?:string|null;total:number;estimatedCogs:number;createdAt:string;items:{name:string;qty:number;lineTotal:number}[]};
const nextStatus:Record<string,string|undefined>={placed:"accepted",accepted:"preparing",preparing:"ready",ready:"completed"};
async function readJson<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{cache:"no-store",...init,headers:{"content-type":"application/json",...(init?.headers||{})}});const body=await response.json();if(!response.ok)throw new Error(body.error||"Request failed");return body as T}

export function ProductionOperations({locations}:{locations:Location[]}){
 const [locationId,setLocationId]=useState(locations[0]?.id||"");const [orders,setOrders]=useState<Order[]>([]);const [menu,setMenu]=useState<MenuItem[]>([]);const [inventory,setInventory]=useState<InventoryItem[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [menuItemId,setMenuItemId]=useState("");const [qty,setQty]=useState(1);
 const location=useMemo(()=>locations.find(x=>x.id===locationId),[locations,locationId]);
 async function load(){if(!locationId)return;setBusy(true);setError("");try{const [o,m,i]=await Promise.all([readJson<{orders:Order[]}>(`/api/workspace/orders?locationId=${encodeURIComponent(locationId)}`),readJson<{items:MenuItem[]}>(`/api/workspace/menu?locationId=${encodeURIComponent(locationId)}`),readJson<{items:InventoryItem[]}>(`/api/workspace/inventory?locationId=${encodeURIComponent(locationId)}`)]);setOrders(o.orders);setMenu(m.items);setInventory(i.items);setMenuItemId(v=>v||m.items[0]?.id||"")}catch(e){setError(e instanceof Error?e.message:"Unable to load operations")}finally{setBusy(false)}}
 useEffect(()=>{void load()},[locationId]);
 async function createOrder(){if(!menuItemId||!locationId)return;setBusy(true);setError("");try{await readJson("/api/workspace/orders",{method:"POST",body:JSON.stringify({locationId,channel:"staff",items:[{menuItemId,qty}]})});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create order");setBusy(false)}}
 async function advance(order:Order,status:string){setBusy(true);setError("");try{await readJson("/api/workspace/orders",{method:"PATCH",body:JSON.stringify({locationId,orderId:order.id,status})});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update order");setBusy(false)}}
 const lowStock=inventory.filter(x=>Number(x.theoreticalQty)<=Number(x.reorderPoint));const revenue=orders.filter(x=>x.status==="completed").reduce((s,x)=>s+Number(x.total||0),0);const contribution=orders.filter(x=>x.status==="completed").reduce((s,x)=>s+Number(x.total||0)-Number(x.estimatedCogs||0),0);
 if(!locations.length)return <section className="ops-empty">Create a location to activate operations.</section>;
 return <section className="ops-shell"><div className="ops-toolbar"><div><span>LIVE OPERATIONS</span><h3>{location?.name||"Location"}</h3></div><div><select value={locationId} onChange={e=>setLocationId(e.target.value)}>{locations.map(x=><option key={x.id} value={x.id}>{x.name} · {x.city}</option>)}</select><button onClick={()=>void load()} disabled={busy}><RefreshCcw size={14}/> Refresh</button></div></div>{error&&<p className="ops-error">{error}</p>}<div className="ops-kpis"><article><ClipboardList/><b>{orders.filter(x=>!["completed","cancelled"].includes(x.status)).length}</b><span>open orders</span></article><article><CircleDollarSign/><b>₹{revenue.toFixed(0)}</b><span>recorded revenue</span></article><article><CheckCircle2/><b>₹{contribution.toFixed(0)}</b><span>estimated contribution</span></article><article><PackageSearch/><b>{lowStock.length}</b><span>low-stock items</span></article></div><div className="ops-grid"><div className="ops-panel"><div className="ops-panel-head"><div><span>ORDER ENTRY</span><h4>Create staff order</h4></div></div><div className="ops-order-entry"><select value={menuItemId} onChange={e=>setMenuItemId(e.target.value)}>{menu.map(x=><option key={x.id} value={x.id}>{x.name} · ₹{x.price}</option>)}</select><input type="number" min={1} max={100} value={qty} onChange={e=>setQty(Math.max(1,Math.min(100,Number(e.target.value)||1)))}/><button disabled={busy||!menuItemId} onClick={createOrder}>Place order</button></div><div className="ops-orders">{orders.length===0?<p>No production orders yet.</p>:orders.slice(0,20).map(order=><article key={order.id}><div><b>{order.items.map(x=>`${x.qty}× ${x.name}`).join(", ")}</b><span>{order.channel}{order.tableLabel?` · ${order.tableLabel}`:""} · ₹{Number(order.total).toFixed(0)}</span></div><strong>{order.status}</strong><div>{nextStatus[order.status]&&<button disabled={busy} onClick={()=>advance(order,nextStatus[order.status]!)}>{nextStatus[order.status]}</button>}{!["completed","cancelled"].includes(order.status)&&<button className="danger" disabled={busy} onClick={()=>advance(order,"cancelled")}>cancel</button>}</div></article>)}</div></div><div className="ops-panel"><div className="ops-panel-head"><div><span>INVENTORY CONTROL</span><h4>Theoretical vs physical</h4></div></div><div className="ops-stock">{inventory.length===0?<p>No inventory masters yet.</p>:inventory.map(item=>{const variance=Number(item.physicalQty)-Number(item.theoreticalQty);return <article key={item.id} className={Number(item.theoreticalQty)<=Number(item.reorderPoint)?"low":""}><div><b>{item.name}</b><span>{item.unit} · ₹{Number(item.unitCost).toFixed(2)} / unit</span></div><div><b>{Number(item.theoreticalQty).toFixed(2)}</b><span>theoretical</span></div><div><b>{Number(item.physicalQty).toFixed(2)}</b><span>physical</span></div><div><b>{variance>0?"+":""}{variance.toFixed(2)}</b><span>variance</span></div></article>})}</div></div></div></section>
}
