"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Building2, Database, LogOut, ShieldCheck } from "lucide-react";

type SessionData={authenticated:boolean;configured:boolean;user?:{name:string;email:string;role:string};organization?:{id:string;name:string}|null;locations?:{id:string;name:string;type:string;city:string}[];error?:string};
export function ProductionConsole(){
 const [data,setData]=useState<SessionData|null>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/auth/session",{cache:"no-store"}).then(async r=>({status:r.status,body:await r.json()})).then(({body})=>setData(body)).catch(()=>setData({authenticated:false,configured:false,error:"Unable to reach account service."})).finally(()=>setLoading(false))},[]);
 async function signOut(){await fetch("/api/auth/sign-out",{method:"POST"});window.location.href="/auth/sign-in"}
 if(loading)return <main className="console-loading">Loading secure workspace…</main>;
 if(!data?.configured)return <main className="console-gate"><Database size={28}/><span>PRODUCTION MODE</span><h1>Connect MongoDB to activate accounts.</h1><p>The meeting demo remains fully usable at <a href="/app">/app</a>. Production signup and persistence intentionally stay unavailable until MONGODB_URI is configured.</p><div><a href="/meeting">Meeting mode</a><a href="/app">Open local demo</a></div></main>;
 if(!data.authenticated)return <main className="console-gate"><ShieldCheck size={28}/><span>AUTHENTICATION REQUIRED</span><h1>Sign in to your production workspace.</h1><p>{data.error||"Your session is missing or expired."}</p><div><a href="/auth/sign-in">Sign in</a><a href="/auth/sign-up">Create owner account</a></div></main>;
 return <main className="production-console"><aside><a href="/" className="console-brand">MUNAFFA</a><span>PRODUCTION FOUNDATION</span><nav><a className="active" href="#workspace">Workspace</a><a href="/app">Meeting demo</a><a href="/meeting">Business brief</a></nav><button onClick={signOut}><LogOut size={14}/> Sign out</button></aside><section><header><div><span>ORGANISATION</span><h1>{data.organization?.name||"Munaffa workspace"}</h1></div><div className="console-user"><b>{data.user?.name}</b><span>{data.user?.email}</span></div></header><div id="workspace" className="console-body"><div className="console-welcome"><span>ACCOUNT ACTIVE</span><h2>Your persistent organisation and locations are ready.</h2><p>This console is the authenticated production boundary. Operational MongoDB modules are being wired behind this session architecture; use the linked meeting workspace for the fully interactive cross-module demonstration meanwhile.</p></div><div className="console-status-grid"><article><ShieldCheck size={20}/><b>HTTP-only session</b><span>Random token stored server-side and hashed before lookup.</span></article><article><Database size={20}/><b>MongoDB connected</b><span>Account data and organisation metadata use production persistence.</span></article><article><Building2 size={20}/><b>{data.locations?.length||0} location{(data.locations?.length||0)===1?"":"s"}</b><span>Created inside your organisation during onboarding.</span></article></div><div className="console-locations"><div><span>LOCATIONS</span><h3>Operating properties</h3></div>{data.locations?.map(location=><article key={location.id}><Building2 size={20}/><div><b>{location.name}</b><span>{location.type} · {location.city}</span></div><a href={`/app?location=${location.id}`}>Open demo workflow <ArrowRight size={14}/></a></article>)}</div></div></section></main>
}
