"use client";
import { useMemo, useState } from "react";
import { BarChart3, Building2, ChefHat, CircleDollarSign, ClipboardList, PackageSearch, RotateCcw, Settings, ShoppingCart, Star, Users, Warehouse } from "lucide-react";
import { useDemoWorkspace } from "@/lib/demoWorkspace";
import type { LocationType, OrderStatus, TeamRole } from "@/lib/workspaceTypes";

type View="overview"|"orders"|"inventory"|"purchasing"|"guests"|"profit"|"locations"|"team"|"settings";
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
const nav:{id:View;label:string;icon:typeof BarChart3}[]=[{id:"overview",label:"Overview",icon:BarChart3},{id:"orders",label:"Orders & KDS",icon:ChefHat},{id:"inventory",label:"Inventory",icon:Warehouse},{id:"purchasing",label:"Purchasing",icon:ShoppingCart},{id:"guests",label:"Guests",icon:Star},{id:"profit",label:"Profit",icon:CircleDollarSign},{id:"locations",label:"Locations",icon:Building2},{id:"team",label:"Team",icon:Users},{id:"settings",label:"Settings",icon:Settings}];
const nextLabel:Record<OrderStatus,string>={accepted:"Start prep",preparing:"Mark ready",ready:"Complete",completed:"Completed"};

export function WorkspaceApp(){
 const [view,setView]=useState<View>("overview");
 const s=useDemoWorkspace();
 const active=s.locations.find(x=>x.id===s.activeLocationId)??s.locations[0];
 const orders=s.orders.filter(x=>x.locationId===s.activeLocationId);
 const inventory=s.inventory.filter(x=>x.locationId===s.activeLocationId);
 const issues=s.guestIssues.filter(x=>x.locationId===s.activeLocationId);
 const finance=s.finance.filter(x=>x.locationId===s.activeLocationId);
 const revenue=finance.filter(x=>x.type==="revenue").reduce((a,b)=>a+b.amount,0);
 const expense=finance.filter(x=>x.type==="expense").reduce((a,b)=>a+b.amount,0);
 const low=inventory.filter(x=>x.theoreticalQty<=x.reorderPoint).length;
 const variance=inventory.reduce((sum,x)=>sum+Math.abs(x.theoreticalQty-x.physicalQty)*x.unitCost,0);
 return <main className="workspace-shell">
  <aside className="workspace-sidebar">
   <a href="/" className="workspace-brand"><i>M</i><span>Munaffa</span></a>
   <div className="demo-badge">MEETING DEMO · LOCAL DATA</div>
   <nav>{nav.map(item=>{const Icon=item.icon;return <button key={item.id} className={view===item.id?"active":""} onClick={()=>setView(item.id)}><Icon size={16}/><span>{item.label}</span></button>})}</nav>
   <a className="back-site" href="/">← Cinematic site</a>
  </aside>
  <section className="workspace-main">
   <header className="workspace-topbar"><div><span>ACTIVE LOCATION</span><select value={s.activeLocationId} onChange={e=>s.setActiveLocation(e.target.value)}>{s.locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="topbar-meta"><b>{active?.city}</b><span>{active?.type.replace("-"," ")}</span></div></header>
   <div className="workspace-content">
    {view==="overview"&&<Overview orders={orders.length} activeOrders={orders.filter(x=>x.status!=="completed").length} revenue={revenue} contribution={revenue-expense} low={low} openIssues={issues.filter(x=>x.status==="open").length} variance={variance}/>} 
    {view==="orders"&&<OrdersView/>}
    {view==="inventory"&&<InventoryView/>}
    {view==="purchasing"&&<PurchasingView/>}
    {view==="guests"&&<GuestsView/>}
    {view==="profit"&&<ProfitView/>}
    {view==="locations"&&<LocationsView/>}
    {view==="team"&&<TeamView/>}
    {view==="settings"&&<SettingsView/>}
   </div>
  </section>
 </main>
}

function Title({eyebrow,title,body}:{eyebrow:string;title:string;body:string}){return <div className="workspace-title"><span>{eyebrow}</span><h1>{title}</h1><p>{body}</p></div>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <article className="metric-card"><span>{label}</span><strong>{value}</strong><p>{note}</p></article>}
function Overview({orders,activeOrders,revenue,contribution,low,openIssues,variance}:{orders:number;activeOrders:number;revenue:number;contribution:number;low:number;openIssues:number;variance:number}){return <><Title eyebrow="OWNER COMMAND" title="See what needs attention." body="This demo computes its cards from the shared workspace state. Change orders, stock, purchases or guest recovery and come back here."/><div className="metrics-grid"><Metric label="Recorded revenue" value={money.format(revenue)} note="Revenue events in this demo location"/><Metric label="Recorded contribution" value={money.format(contribution)} note="Revenue minus recorded expenses"/><Metric label="Active orders" value={String(activeOrders)} note={`${orders} total orders in workspace`}/><Metric label="Stock variance value" value={money.format(variance)} note="Illustrative value of count variance"/><Metric label="Low-stock items" value={String(low)} note="Theoretical quantity at/below reorder point"/><Metric label="Open guest recovery" value={String(openIssues)} note="Guest issues that still need action"/></div><div className="signal-panel"><h2>Operational signals</h2><div>{activeOrders>2&&<p>Kitchen queue is building. Review active orders.</p>}{variance>500&&<p>Physical count differs materially from theoretical stock.</p>}{openIssues>0&&<p>{openIssues} guest recovery item{openIssues===1?"":"s"} need attention.</p>}{low>0&&<p>{low} inventory item{low===1?" is":"s are"} at or below reorder point.</p>}{activeOrders<=2&&variance<=500&&openIssues===0&&low===0&&<p>No high-priority signal in the local demo workspace.</p>}</div></div></>}

function OrdersView(){const s=useDemoWorkspace();const [menuId,setMenuId]=useState("");const [ref,setRef]=useState("Table 14");const menu=s.menu.filter(x=>x.locationId===s.activeLocationId);const orders=s.orders.filter(x=>x.locationId===s.activeLocationId);function create(){const selected=menuId||menu[0]?.id;if(selected)s.addOrder({serviceRef:ref||"Walk-in",lines:[{menuId:selected,qty:1}],channel:"staff"})}return <><Title eyebrow="SERVICE → KITCHEN" title="Orders move through one queue." body="Advance an order to completion and Munaffa will deduct its recipe quantities from theoretical inventory and record the sale as revenue."/><div className="workspace-form inline-form"><select value={menuId} onChange={e=>setMenuId(e.target.value)}><option value="">Choose menu item</option>{menu.map(x=><option key={x.id} value={x.id}>{x.name} · {money.format(x.price)}</option>)}</select><input value={ref} onChange={e=>setRef(e.target.value)} placeholder="Table / room"/><button onClick={create}>Create order</button></div><div className="order-board">{orders.map(o=><article key={o.id}><div><span>{o.channel==="guest-qr"?"GUEST QR":"STAFF"}</span><h3>{o.serviceRef}</h3><p>{o.items.map(x=>`${x.qty}× ${x.name}`).join(", ")}</p></div><div><b>{money.format(o.total)}</b><em className={`status ${o.status}`}>{o.status}</em><button disabled={o.status==="completed"} onClick={()=>s.advanceOrder(o.id)}>{nextLabel[o.status]}</button></div></article>)}</div></>}

function InventoryView(){const s=useDemoWorkspace();const items=s.inventory.filter(x=>x.locationId===s.activeLocationId);return <><Title eyebrow="EXPECTED VS PHYSICAL" title="Count reality separately." body="Theoretical stock changes from orders and purchases. Physical stock changes only when somebody records a count. The difference is variance—not automatically theft."/><div className="data-table inventory-table"><div className="table-head"><span>Item</span><span>Theoretical</span><span>Physical count</span><span>Variance</span><span>Value</span></div>{items.map(item=><div className="table-row" key={item.id}><span><b>{item.name}</b><small>Reorder {item.reorderPoint} {item.unit}</small></span><span>{item.theoreticalQty.toFixed(2)} {item.unit}</span><span><input type="number" step="0.1" value={item.physicalQty} onChange={e=>s.countInventory(item.id,Number(e.target.value))}/></span><span className={Math.abs(item.theoreticalQty-item.physicalQty)>.5?"warn":""}>{(item.physicalQty-item.theoreticalQty).toFixed(2)} {item.unit}</span><span>{money.format(Math.abs(item.physicalQty-item.theoreticalQty)*item.unitCost)}</span></div>)}</div></>}

function PurchasingView(){const s=useDemoWorkspace();const items=s.inventory.filter(x=>x.locationId===s.activeLocationId);const [itemId,setItemId]=useState("");const [supplier,setSupplier]=useState("FreshRoute Foods");const [qty,setQty]=useState(5);const [cost,setCost]=useState(300);function receive(){const chosen=itemId||items[0]?.id;if(chosen)s.receivePurchase(supplier,chosen,qty,cost)}const purchases=s.purchases.filter(x=>x.locationId===s.activeLocationId);return <><Title eyebrow="PROCUREMENT" title="Receive stock once. Record cost once." body="A received purchase increases theoretical inventory and creates the linked expense event in the same action."/><div className="workspace-form purchase-form"><input value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Supplier"/><select value={itemId} onChange={e=>setItemId(e.target.value)}><option value="">Choose stock item</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="number" min=".1" step=".1" value={qty} onChange={e=>setQty(Number(e.target.value))}/><input type="number" min="0" value={cost} onChange={e=>setCost(Number(e.target.value))}/><button onClick={receive}>Receive purchase</button></div><div className="activity-list">{purchases.length? purchases.map(p=><article key={p.id}><div><b>{p.supplier}</b><span>{p.itemName} · {p.quantity} units</span></div><strong>{money.format(p.total)}</strong></article>):<p className="empty-state">No new purchase receipts yet. Receive one above and then check Inventory + Profit.</p>}</div></>}

function GuestsView(){const s=useDemoWorkspace();const [guest,setGuest]=useState("Walk-in guest");const [rating,setRating]=useState(3);const [note,setNote]=useState("Service took longer than expected.");const issues=s.guestIssues.filter(x=>x.locationId===s.activeLocationId);return <><Title eyebrow="GUEST RECOVERY" title="Turn feedback into an action queue." body="Capture a concern, assign attention, then close it. This meeting demo keeps the data in your browser only."/><div className="workspace-form guest-form"><input value={guest} onChange={e=>setGuest(e.target.value)} placeholder="Guest label"/><input type="number" min="1" max="5" value={rating} onChange={e=>setRating(Number(e.target.value))}/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Feedback"/><button onClick={()=>s.addGuestIssue(guest,rating,note)}>Add feedback</button></div><div className="activity-list">{issues.map(x=><article key={x.id}><div><b>{x.guest} · {x.rating}/5</b><span>{x.note}</span></div><button disabled={x.status==="resolved"} onClick={()=>s.resolveGuestIssue(x.id)}>{x.status==="resolved"?"Resolved":"Resolve"}</button></article>)}</div></>}

function ProfitView(){const s=useDemoWorkspace();const events=s.finance.filter(x=>x.locationId===s.activeLocationId);const revenue=events.filter(x=>x.type==="revenue").reduce((a,b)=>a+b.amount,0);const expenses=events.filter(x=>x.type==="expense").reduce((a,b)=>a+b.amount,0);return <><Title eyebrow="RECORDED MONEY MOVEMENT" title="See contribution from operational events." body="This is a demo ledger, not accounting software. Completed demo orders become revenue; received purchases become expenses."/><div className="profit-hero"><div><span>Recorded revenue</span><strong>{money.format(revenue)}</strong></div><div><span>Recorded expenses</span><strong>{money.format(expenses)}</strong></div><div className="profit-net"><span>Recorded contribution</span><strong>{money.format(revenue-expenses)}</strong></div></div><div className="activity-list">{events.map(x=><article key={x.id}><div><b>{x.label}</b><span>{new Date(x.createdAt).toLocaleString()}</span></div><strong className={x.type}>{x.type==="expense"?"−":"+"}{money.format(x.amount)}</strong></article>)}</div></>}

function LocationsView(){const s=useDemoWorkspace();const [name,setName]=useState("New Munaffa Location");const [city,setCity]=useState("Delhi");const [type,setType]=useState<LocationType>("restaurant");return <><Title eyebrow="MULTI-PROPERTY" title="One organisation. Many hospitality rhythms." body="Add an outlet/property and switch the active workspace from the top bar."/><div className="workspace-form location-form"><input value={name} onChange={e=>setName(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value as LocationType)}>{["restaurant","cafe","hotel","resort","qsr","cloud-kitchen"].map(x=><option key={x}>{x}</option>)}</select><input value={city} onChange={e=>setCity(e.target.value)}/><button onClick={()=>s.addLocation(name,type,city)}>Add location</button></div><div className="location-grid">{s.locations.map(x=><button key={x.id} onClick={()=>s.setActiveLocation(x.id)} className={s.activeLocationId===x.id?"active":""}><Building2 size={22}/><b>{x.name}</b><span>{x.type.replace("-"," ")} · {x.city}</span></button>)}</div></>}

function TeamView(){const s=useDemoWorkspace();const [name,setName]=useState("New teammate");const [role,setRole]=useState<TeamRole>("Manager");return <><Title eyebrow="TEAM" title="Show roles without pretending permissions are live." body="The production version will enforce RBAC server-side. This meeting mode demonstrates the workflow and labels invitations honestly."/><div className="workspace-form inline-form"><input value={name} onChange={e=>setName(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value as TeamRole)}>{["Owner","Manager","Cashier","Kitchen","Inventory","Service"].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>s.inviteMember(name,role)}>Create demo invite</button></div><div className="activity-list">{s.team.map(x=><article key={x.id}><div><b>{x.name}</b><span>{x.role}</span></div><em className={`status ${x.status}`}>{x.status}</em></article>)}</div></>}

function SettingsView(){const s=useDemoWorkspace();const stats=useMemo(()=>({orders:s.orders.length,locations:s.locations.length,events:s.finance.length}),[s.orders.length,s.locations.length,s.finance.length]);return <><Title eyebrow="DEMO CONTROL" title="Meeting-safe reset and architecture status." body="Nothing here claims a production database is connected. The production adapter is configured separately with environment variables."/><div className="settings-grid"><article><ClipboardList size={20}/><b>{stats.orders} orders</b><span>Persisted in this browser demo</span></article><article><Building2 size={20}/><b>{stats.locations} locations</b><span>Shared demo organisation</span></article><article><PackageSearch size={20}/><b>{stats.events} ledger events</b><span>Operationally generated demo records</span></article></div><button className="danger-button" onClick={()=>s.resetDemo()}><RotateCcw size={15}/> Reset meeting demo</button></>}
