import type { FinanceEvent, GuestIssue, InventoryItem, Location, MenuItem, Order, TeamMember } from "./workspaceTypes";
const now=()=>new Date().toISOString();
export const seedLocations:Location[]=[{id:"loc_civil",name:"Munaffa House · Civil Lines",type:"restaurant",city:"Delhi"},{id:"loc_cafe",name:"Munaffa Café · Noida",type:"cafe",city:"Noida"},{id:"loc_hotel",name:"Munaffa Stay · Jaipur",type:"hotel",city:"Jaipur"}];
export const seedInventory:InventoryItem[]=[{id:"inv_paneer",locationId:"loc_civil",name:"Paneer",unit:"kg",theoreticalQty:18.4,physicalQty:17.7,reorderPoint:8,unitCost:340},{id:"inv_cream",locationId:"loc_civil",name:"Fresh cream",unit:"L",theoreticalQty:9.8,physicalQty:9.1,reorderPoint:4,unitCost:230},{id:"inv_tomato",locationId:"loc_civil",name:"Tomato",unit:"kg",theoreticalQty:25.6,physicalQty:24.9,reorderPoint:10,unitCost:44},{id:"inv_coffee",locationId:"loc_cafe",name:"Coffee beans",unit:"kg",theoreticalQty:6.2,physicalQty:5.9,reorderPoint:2.5,unitCost:1120},{id:"inv_milk",locationId:"loc_cafe",name:"Milk",unit:"L",theoreticalQty:31,physicalQty:30.2,reorderPoint:12,unitCost:66}];
export const seedMenu:MenuItem[]=[{id:"menu_paneer",locationId:"loc_civil",name:"Smoked Paneer Tikka",category:"Signature",price:495,recipe:[{inventoryId:"inv_paneer",qty:.18},{inventoryId:"inv_cream",qty:.04},{inventoryId:"inv_tomato",qty:.08}]},{id:"menu_curry",locationId:"loc_civil",name:"House Tomato Curry",category:"Mains",price:425,recipe:[{inventoryId:"inv_tomato",qty:.22},{inventoryId:"inv_cream",qty:.06}]},{id:"menu_cappuccino",locationId:"loc_cafe",name:"Cappuccino",category:"Coffee",price:225,recipe:[{inventoryId:"inv_coffee",qty:.018},{inventoryId:"inv_milk",qty:.18}]},{id:"menu_flatwhite",locationId:"loc_cafe",name:"Flat White",category:"Coffee",price:245,recipe:[{inventoryId:"inv_coffee",qty:.02},{inventoryId:"inv_milk",qty:.16}]}];
export const seedOrders:Order[]=[{id:"ord_1042",locationId:"loc_civil",serviceRef:"Table 08",channel:"staff",status:"preparing",items:[{menuId:"menu_paneer",name:"Smoked Paneer Tikka",qty:2,price:495}],total:990,createdAt:now()},{id:"ord_1043",locationId:"loc_civil",serviceRef:"Guest QR · Table 12",channel:"guest-qr",status:"accepted",items:[{menuId:"menu_curry",name:"House Tomato Curry",qty:1,price:425}],total:425,createdAt:now()}];
export const seedGuestIssues:GuestIssue[]=[{id:"guest_1",locationId:"loc_civil",guest:"Guest A",channel:"Dine-in",rating:3,note:"Main course arrived later than expected.",status:"open",createdAt:now()}];
export const seedFinance:FinanceEvent[]=[{id:"fin_1",locationId:"loc_civil",type:"revenue",label:"Recorded settlements",amount:42860,createdAt:now()},{id:"fin_2",locationId:"loc_civil",type:"expense",label:"Supplier receipts",amount:17640,createdAt:now()}];
export const seedTeam:TeamMember[]=[{id:"tm_1",name:"Workspace Owner",role:"Owner",status:"active"},{id:"tm_2",name:"Demo Manager",role:"Manager",status:"active"},{id:"tm_3",name:"Kitchen Lead",role:"Kitchen",status:"active"}];
